import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { coverErrors, type CoverDraft } from "../../router-app/lib/cover-editor";

const migration=await readFile("supabase/migrations/202609250001_cover_editor.sql","utf8");
const admin="00000000-0000-4000-8000-000000000001",moderator="00000000-0000-4000-8000-000000000002",editor="00000000-0000-4000-8000-000000000003",issue="10000000-0000-4000-8000-000000000001",feature="20000000-0000-4000-8000-000000000001";
async function fixture(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create table profiles(id uuid primary key,role text,account_status text);create table issues(id uuid primary key,issue_number integer unique,slug text unique,title text,year integer,month integer,status text,updated_at timestamptz default now());create table features(id uuid primary key,issue_id uuid references issues,status text,lifecycle_status text);create table editorial_documents(feature_id uuid primary key,lifecycle_status text);create function open_panel_role() returns text language sql stable as $$select role from profiles where id=auth.uid()$$;create function require_handbook_acceptance() returns void language plpgsql as $$begin end$$;insert into profiles values('${admin}','admin','active'),('${moderator}','moderator','active'),('${editor}','member','active');insert into issues values('${issue}',1,'issue-one','Issue One',2026,9,'current',now());insert into features values('${feature}','${issue}','published','final_panel');`);await db.exec(migration);return db;}
async function as(db:PGlite,id:string){await db.exec("reset role");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec("set role authenticated");}
const payload={issue_id:issue,issue_number:"1",slug:"issue-one",title:"Issue One",year:"2026",month:"9",cover_art:"/assets/cover.png",cover_art_alt:"Ink drawing of a pilot",cover_art_credit:"Artist",lead_feature_id:feature,lead_headline:"The future starts here",cover_theme:"Issue theme",secondary_cover_lines:[{position:"left-rail",headline:"Inside the issue"}],editor_note_teaser:"A short note",featuring_line:"Featuring KOMA contributors",cover_preset:"minimal"};

test("Cover Editor is limited to moderator/admin and persists safe cover metadata",async()=>{const db=await fixture();try{await as(db,editor);await assert.rejects(db.query("select save_issue_cover($1)",[payload]),/Moderator access required/);await as(db,moderator);await db.query("select save_issue_cover($1)",[payload]);await db.exec("reset role");const row=(await db.query<any>("select cover_art_alt,lead_feature_id,cover_preset from issues where id=$1",[issue])).rows[0];assert.deepEqual(row,{cover_art_alt:payload.cover_art_alt,lead_feature_id:feature,cover_preset:"minimal"});await as(db,admin);await db.query("select save_issue_cover($1)",[{...payload,cover_preset:"archive-classic"}]);}finally{await db.close();}});

test("archive transition rejects incomplete covers and accepts a valid published-panel cover",async()=>{const db=await fixture();try{await as(db,moderator);await db.exec("reset role");await assert.rejects(db.query("update issues set status='archived' where id=$1",[issue]),/Cover is not ready/);await as(db,moderator);await db.query("select save_issue_cover($1)",[payload]);await db.exec("reset role");await db.query("update issues set status='archived' where id=$1",[issue]);assert.equal((await db.query<any>("select status from issues where id=$1",[issue])).rows[0].status,"archived");}finally{await db.close();}});

test("client validation requires artwork alt, lead and a published panel",()=>{const draft={...payload,cover_art_alt:"",lead_feature_id:""} as CoverDraft;const errors=coverErrors(draft,[]);assert.match(errors.cover_art_alt,/accessible/);assert.match(errors.lead_feature_id,/published panel/);});

test("route, archive card and writing surfaces preserve access, visibility and spellcheck contracts",async()=>{const [route,client,routes,archive,server,editorial,workshop,builder]=await Promise.all([readFile("router-app/routes/cover-editor.tsx","utf8"),readFile("router-app/components/CoverEditorClient.tsx","utf8"),readFile("router-app/routes.ts","utf8"),readFile("router-app/components/publication/ArchiveShelf.tsx","utf8"),readFile("router-app/lib/publication.server.ts","utf8"),readFile("router-app/routes/editorial.tsx","utf8"),readFile("router-app/components/open-panel/WorkshopClient.tsx","utf8"),readFile("router-app/components/ArticleSectionBuilder.tsx","utf8")]);assert.match(routes,/route\("cover-editor"/);assert.match(route,/\["moderator","admin"\]/);assert.match(route,/save_issue_cover/);assert.match(route,/close_current_issue/);assert.match(archive,/issue\.cover_art/);assert.match(server,/issue\.status !== "draft"/);for(const source of [client,editorial,workshop,builder])assert.match(source,/spellCheck/);assert.doesNotMatch(editorial,/text-align|align-center|align-right/);assert.doesNotMatch(workshop,/text-align|align-center|align-right/);});
