import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { LatestUploadCoordinator } from "../../router-app/lib/latest-upload";
import { composerDraftSchema, createComposerSection, moveComposerSection, removeComposerSection, updateComposerSection } from "../../router-app/lib/editorial-alpha";
import { validateSections } from "../../router-app/lib/editorial-validation";

test("new replacements invalidate older upload completions",()=>{const uploads=new LatestUploadCoordinator();const first=uploads.begin("image-1"),second=uploads.begin("image-1");assert.equal(first.signal.aborted,true);assert.equal(first.current(),false);assert.equal(second.current(),true);second.finish();});

test("removal invalidates a pending upload so it cannot restore an image",()=>{const uploads=new LatestUploadCoordinator();const pending=uploads.begin("image-1");uploads.cancel("image-1");assert.equal(pending.signal.aborted,true);assert.equal(pending.current(),false);});

test("image edits and validation remain attached to stable section IDs",()=>{const image=createComposerSection("image",1),paragraph=createComposerSection("paragraph",2);let sections=[image,paragraph];sections=updateComposerSection(sections,image.id,{url:"/assets/first.png",alt:"First description"});sections=moveComposerSection(sections,image.id,"down");sections=updateComposerSection(sections,image.id,{url:"/assets/latest.png",alt:"Latest description"});assert.deepEqual(sections.find(section=>section.id===image.id),{...image,url:"/assets/latest.png",alt:"Latest description"});assert.equal(validateSections(sections).some(issue=>issue.sectionId===image.id),false);sections=updateComposerSection(sections,image.id,{alt:""});assert.match(validateSections(sections).find(issue=>issue.sectionId===image.id&&issue.field==="alt")!.message,/screen readers/);sections=removeComposerSection(sections,image.id);assert.equal(validateSections(sections).some(issue=>issue.sectionId===image.id),false);});

test("private drafts retain incomplete image state while submission validation stays explicit",()=>{const image=createComposerSection("image",3);assert.equal(composerDraftSchema.safeParse({title:"Draft",slug:"draft-panel",summary:"Draft summary",sectionsJson:JSON.stringify([image]),status:"draft"}).success,true);const issues=validateSections([image]);assert.ok(issues.some(issue=>issue.field==="url"));assert.ok(issues.some(issue=>issue.field==="alt"));});

test("all upload surfaces use latest-request guards and recoverable controls",async()=>{const [editorial,builder,cover,workshop,coverRoute]=await Promise.all([readFile("router-app/routes/editorial.tsx","utf8"),readFile("router-app/components/ArticleSectionBuilder.tsx","utf8"),readFile("router-app/components/CoverEditorClient.tsx","utf8"),readFile("router-app/components/open-panel/WorkshopClient.tsx","utf8"),readFile("router-app/routes/cover-editor.tsx","utf8")]);for(const source of [editorial,cover,workshop]){assert.match(source,/LatestUploadCoordinator/);assert.match(source,/ticket\.current\(\)/);assert.match(source,/signal:ticket\.signal/);}assert.match(editorial,/Record<string/);assert.match(builder,/REMOVE IMAGE/);assert.match(cover,/REMOVE COVER ARTWORK/);assert.match(workshop,/Screenshot removed/);assert.match(coverRoute,/form\.get\("intent"\)==="archive"&&Object\.keys\(errors\)\.length/);});
