-- Ecosystem + Phase 1 synthetic database-role smoke. Every record and audit entry is rolled back.
begin;
set local statement_timeout='45s';
set local lock_timeout='3s';
do $$
declare actor uuid; member_id uuid:=gen_random_uuid(); editor_id uuid:=gen_random_uuid(); moderator_id uuid:=gen_random_uuid(); iid uuid:=gen_random_uuid(); fid uuid:=gen_random_uuid(); drop_id uuid:=gen_random_uuid(); draft_id uuid:=gen_random_uuid(); contribution uuid; report uuid; v public.handbook_versions; payload jsonb; snapshot jsonb; n integer; year_value integer; private_path text; media_ref uuid; inbox_id uuid; inbox_count integer; original_version bigint; current_version bigint; edit_draft uuid:=gen_random_uuid(); racing_draft uuid:=gen_random_uuid();
begin
 select p.id into strict actor from public.profiles p where p.role='admin' and p.account_status='active' and exists(select 1 from public.handbook_acceptances a join public.handbook_versions h on h.id=a.handbook_version_id and h.active where a.user_id=p.id and a.statement_version=h.statement_version) limit 1;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into auth.users(id,email,raw_user_meta_data) values(member_id,'phase1-'||member_id||'@example.invalid','{"display_name":"Phase 1 private fixture"}'),(editor_id,'phase1-'||editor_id||'@example.invalid','{}'),(moderator_id,'phase1-'||moderator_id||'@example.invalid','{}');
 update public.profiles set role='moderator' where id=moderator_id;
 insert into public.editorial_access_grants(user_id,access_level,granted_by) values(editor_id,'editor',actor);
 select * into strict v from public.handbook_versions where active;
 select y into year_value from generate_series(2100,2199) y where not exists(select 1 from public.issues where year=y and month=12) limit 1;
 insert into public.issues(id,issue_number,slug,title,year,month,status,opens_at,closes_at,created_by) values(iid,(select max(issue_number)+10000 from public.issues),'phase1-'||iid,'Rollback-only Phase 1 fixture',year_value,12,'finalising',now()-interval '1 day',now()+interval '1 day',actor);
 insert into public.weekly_drops(id,issue_id,week_number,label,status,published_at) values(drop_id,iid,1,'Rollback-only test','published',now());
 insert into public.features(id,issue_id,weekly_drop_id,slug,title,status,lifecycle_status) values(fid,iid,drop_id,'phase1-'||fid,'Rollback-only Phase 1 fixture','published','open_panel');
 insert into public.editorial_documents(feature_id,author_id,schema_version,working_document,lifecycle_status) values(fid,editor_id,1,'{"schemaVersion":1,"modules":[]}','published');
 foreach actor in array array[member_id,editor_id,moderator_id] loop
  perform set_config('request.jwt.claim.sub',actor::text,true);set local role authenticated;
  perform public.accept_handbook(v.id,v.content_hash,v.statement_version,true);reset role;
 end loop;
 perform set_config('request.jwt.claim.sub',member_id::text,true);set local role authenticated;
 private_path:=member_id||'/'||gen_random_uuid()||'.png';
 insert into storage.objects(bucket_id,name,owner_id) values('open-panel-screenshots',private_path,member_id::text);
 payload:=jsonb_build_object('feature_id',fid,'type','Tip','title','Rollback-only private proposal','body','Private proposal retained across an ambiguous submission response.','target_section','Contribution','source_url','','media_url','','screenshot_path',private_path,'public_credit','Anonymous Panelist','publication_consent',true);
 perform public.save_workshop_draft(draft_id,fid,0,'{"title":"Recoverable unfinished writing"}');
 begin perform public.submit_workshop_draft(draft_id,1);raise exception 'Incomplete submission succeeded';exception when not_null_violation or check_violation or insufficient_privilege or raise_exception then if sqlerrm='Incomplete submission succeeded' then raise;end if;end;
 perform public.save_workshop_draft(draft_id,fid,1,payload);
 begin perform public.save_workshop_draft(draft_id,fid,1,payload||'{"body":"stale writing"}');raise exception 'Stale overwrite accepted';exception when sqlstate 'P4090' then null;end;
 contribution:=public.submit_workshop_draft(draft_id,2);
 if public.submit_workshop_draft(draft_id,2)<>contribution then raise exception 'Duplicate submission';end if;
 if (select count(*) from public.contributions where author_id=member_id)<>1 then raise exception 'Canonical duplicate';end if;
 reset role;update public.features set deadline_override=now()-interval '1 hour' where id=fid;set local role authenticated;
 begin perform public.save_contribution(payload||jsonb_build_object('request_key',gen_random_uuid()));raise exception 'Closed panel accepted new submission';exception when insufficient_privilege or raise_exception then if sqlerrm='Closed panel accepted new submission' then raise;end if;end;
 select edit_version into original_version from public.contributions where id=contribution;
 perform public.save_workshop_draft(edit_draft,fid,0,payload||jsonb_build_object('title','Corrected private proposal','expected_edit_version',original_version::text),contribution);
 if public.submit_workshop_draft(edit_draft,1)<>contribution or public.submit_workshop_draft(edit_draft,1)<>contribution then raise exception 'Correction duplicated contribution';end if;
 if (select count(*) from public.contribution_edit_history where contribution_id=contribution)<>1 then raise exception 'Correction audit missing';end if;
 if not exists(select 1 from public.contribution_edit_history h where h.contribution_id=contribution and h.snapshot->>'title'='Rollback-only private proposal') then raise exception 'Original text not retained';end if;
 begin perform public.save_contribution(payload||jsonb_build_object('expected_edit_version',original_version::text,'request_key',gen_random_uuid()),contribution);raise exception 'Stale correction accepted';exception when sqlstate 'P4090' then null;end;
 select edit_version into current_version from public.contributions where id=contribution;
 perform public.save_workshop_draft(racing_draft,fid,0,payload||jsonb_build_object('expected_edit_version',current_version::text),contribution);
 perform set_config('request.jwt.claim.sub',moderator_id::text,true);
 begin perform public.moderate_contribution_current(contribution,original_version,'Accepted','Stale screen');raise exception 'Stale review accepted';exception when sqlstate 'P4090' then null;end;
 begin perform public.moderate_contribution(contribution,'Accepted','','','Legacy bypass');raise exception 'Unversioned review allowed';exception when insufficient_privilege then null;end;
 perform public.moderate_contribution_current(contribution,current_version,'In Review','Review started');
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 begin perform public.submit_workshop_draft(racing_draft,1);raise exception 'Concurrent review overwritten';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',moderator_id::text,true);
 perform public.moderate_contribution_current(contribution,(select edit_version from public.contributions where id=contribution),'Changes Requested','Please correct the wording');
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 perform public.save_workshop_draft(racing_draft,fid,1,payload||jsonb_build_object('expected_edit_version',(select edit_version::text from public.contributions where id=contribution)),contribution);
 perform public.submit_workshop_draft(racing_draft,2);
 if exists(select 1 from public.contributions c where c.id=contribution and (c.reviewed_at is not null or c.moderator_id is not null or c.status<>'Submitted')) then raise exception 'Returned review not invalidated';end if;
 perform public.set_feature_saved(fid,true);
 report:=public.submit_correction(fid,'Safety concern','Rollback-only private reporting check.','');
 if (select count(*) from public.correction_reports where id=report)<>1 then raise exception 'Own report missing';end if;
 if public.cover_committee_access() then raise exception 'Member cover access';end if;
 perform set_config('request.jwt.claim.sub',editor_id::text,true);
 if exists(select 1 from public.saved_features where user_id=member_id) or exists(select 1 from public.workshop_drafts where user_id=member_id) or exists(select 1 from public.correction_reports where id=report) then raise exception 'Cross-user private read';end if;
 if exists(select 1 from public.contribution_edit_history where contribution_id=contribution) then raise exception 'Cross-user history access';end if;
 begin perform public.save_contribution(payload||jsonb_build_object('expected_edit_version',current_version::text,'request_key',gen_random_uuid()),contribution);raise exception 'Cross-user correction allowed';exception when insufficient_privilege then null;end;
 if not exists(select 1 from public.editorial_documents where feature_id=fid and author_id=editor_id) then raise exception 'Editor own provenance unavailable';end if;
 perform set_config('request.jwt.claim.sub',moderator_id::text,true);
 if not exists(select 1 from public.open_panel_review_inbox() where contribution_id=contribution and author_id=member_id) then raise exception 'Moderator provenance unavailable';end if;
 if not exists(select 1 from public.correction_reports where id=report) then raise exception 'Moderator report unavailable';end if;
 perform public.moderate_contribution_current(contribution,(select edit_version from public.contributions where id=contribution),'Accepted','Rollback-only review');
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 if exists(select 1 from public.my_contribution_publication() where published) then raise exception 'Accepted incorrectly published';end if;
 perform set_config('request.jwt.claim.sub',moderator_id::text,true);
 perform public.prepare_contribution_incorporation(contribution,'Rollback-only heading','Reviewed anonymous text for transactional privacy checks.','Rollback-only preparation');
 begin perform public.review_contribution_incorporation(contribution,'approve','');raise exception 'Self-approval succeeded';exception when insufficient_privilege then null;end;
 reset role;
 select p.id into strict actor from public.profiles p where p.role='admin' and p.account_status='active' and exists(select 1 from public.handbook_acceptances a join public.handbook_versions h on h.id=a.handbook_version_id and h.active where a.user_id=p.id and a.statement_version=h.statement_version) limit 1;
 perform set_config('request.jwt.claim.sub',actor::text,true);set local role authenticated;
 perform public.review_contribution_incorporation(contribution,'approve','');perform public.publish_contribution_incorporation(contribution);
 if not exists(select 1 from public.contributions where id=contribution and author_id=member_id) then raise exception 'Admin provenance missing';end if;
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 perform public.set_member_preferences(array['gaming','manga']);
 if (select interests from public.profiles where id=member_id)<>array['gaming','manga'] then raise exception 'Preferences missing';end if;
 begin perform public.set_member_preferences(array['franchise']);raise exception 'Invalid preferences accepted';exception when invalid_parameter_value then null;end;
 if (select role from public.profiles where id=member_id)<>'member' then raise exception 'Preferences elevated access';end if;
 select count(*) into inbox_count from public.my_editorial_inbox();
 if inbox_count<3 then raise exception 'Editorial feedback missing';end if;
 if (select count(*) from public.my_editorial_inbox())<>inbox_count then raise exception 'Duplicate Inbox delivery';end if;
 if not exists(select 1 from public.my_citation_history() where contribution_id=contribution) then raise exception 'Private recognition missing';end if;
 select id into inbox_id from public.member_inbox order by created_at desc limit 1;
 perform public.set_inbox_read(inbox_id,true);
 if not exists(select 1 from public.member_inbox where id=inbox_id and read_at is not null) then raise exception 'Read state missing';end if;
 perform set_config('request.jwt.claim.sub',editor_id::text,true);
 if exists(select 1 from public.member_inbox where user_id=member_id) or public.set_inbox_read(inbox_id,true) then raise exception 'Cross-user Inbox access';end if;
 begin perform public.deliver_editorial_event(member_id,'forged','published',fid,null,'Forged');raise exception 'Client can forge notifications';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub','',true);set local role anon;
 select jsonb_build_object('additions',(select jsonb_agg(to_jsonb(a)) from public.public_additions a where feature_id=fid),'revisions',(select jsonb_agg(to_jsonb(r)) from public.public_revisions r where feature_id=fid),'citations',(select jsonb_agg(to_jsonb(c)) from public.public_citations c where feature_id=fid),'issue',(select to_jsonb(i) from public.public_issues i where id=iid),'feature',(select to_jsonb(f) from public.public_features f where id=fid)) into snapshot;
 if snapshot is null or snapshot::text like '%'||member_id||'%' or snapshot::text like '%'||editor_id||'%' or snapshot::text like '%'||moderator_id||'%' or snapshot::text like '%'||actor||'%' or snapshot::text like '%'||contribution||'%' or snapshot::text like '%contributor_id%' or snapshot::text like '%'||private_path||'%' then raise exception 'Public identity leak';end if;
 if exists(select 1 from storage.objects where bucket_id='open-panel-screenshots' and name=private_path) then raise exception 'Storage metadata public';end if;
 begin perform count(*) from public.contribution_edit_history;raise exception 'Edit history public';exception when insufficient_privilege then null;end;
 begin perform count(*) from public.member_inbox;raise exception 'Inbox public';exception when insufficient_privilege then null;end;
 begin perform count(*) from public.published_additions;raise exception 'Raw additions public';exception when insufficient_privilege then null;end;
 begin perform count(*) from public.revisions;raise exception 'Raw revisions public';exception when insufficient_privilege then null;end;
 begin perform count(*) from public.issue_cover_candidates;raise exception 'Cover Pool public';exception when insufficient_privilege then null;end;
 reset role;
 select id into strict media_ref from public.publication_media_refs where context_kind='addition' and path=private_path;
 if not exists(select 1 from public.resolve_publication_media(media_ref)) then raise exception 'Published media cannot resolve';end if;
 update public.features set lifecycle_status='taken_down' where id=fid;
 if exists(select 1 from public.resolve_publication_media(media_ref)) then raise exception 'Taken-down media resolves';end if;
 perform set_config('request.jwt.claim.sub',member_id::text,true);set local role authenticated;
 begin perform public.save_contribution(payload||jsonb_build_object('expected_edit_version',(select edit_version::text from public.contributions where id=contribution),'request_key',gen_random_uuid()),contribution);raise exception 'Incorporated content editable';exception when insufficient_privilege then null;end;
 if not exists(select 1 from public.my_citation_history() where contribution_id=contribution) then raise exception 'Takedown erased private recognition';end if;
 if exists(select 1 from public.my_contribution_publication() where published) then raise exception 'Taken-down work called public';end if;
 reset role;
end $$;
rollback;
select 'PASS: correction CAS, idempotency, private original snapshots, stale review/concurrent review rejection, returned review invalidation, publication immutability; ecosystem preferences, private duplicate-safe Inbox/read state, citation history and production rollback-only member/editor/moderator/admin RPC/RLS, drafts, idempotency, private Save/report, independent review, anonymous publication/media and takedown. All synthetic rows rolled back.' as result;
