import { type RouteConfig, index, route } from "@react-router/dev/routes";
export default [
  index("routes/home.tsx"),
  route("robots.txt", "routes/robots.ts"),
  route("sitemap.xml", "routes/sitemap.ts"),
  route("issues/:slug", "routes/issue.tsx"),
  route("features/:slug", "routes/feature.tsx"),
  route("features/:slug/workshop", "routes/workshop.tsx"),
  route("features/:slug/correction", "routes/correction.tsx"),
  route("archive", "routes/archive.tsx"),
  route("about", "routes/about.tsx"),
  route("documents", "routes/documents.tsx"),
  route("documents/platform-notice", "routes/platform-notice.tsx"),
  route("search", "routes/search.tsx"),
  route("handbook", "routes/handbook.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("auth/callback", "routes/auth-callback.tsx"),
  route("member/handbook", "routes/member-handbook.tsx"),
  route("member/workshop/:action", "routes/workshop-action.tsx"),
  route("profile", "routes/profile.tsx"),
  route("profile/settings", "routes/profile-settings.tsx"),
  route("editorial", "routes/editorial.tsx"),
  route("moderation", "routes/moderation.tsx"),
  route("api/open-panel/image", "routes/public-image.ts"),
  route("api/editorial/image", "routes/editorial-image.tsx"),
  route("member/editorial/upload", "routes/editorial-upload.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
