-- Editorial grants and immutable structured document foundation. All media begins private.
create table public.editorial_access_grants (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), access_level text not null check(access_level in ('editor','administrator')), scope_type text not null default 'global', scope_id uuid, granted_by uuid not null references public.profiles(id), granted_at timestamptz not null default now(), revoked_by uuid references public.profiles(id), revoked_at timestamptz, reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index editorial_active_grant on public.editorial_access_grants(user_id,access_level,scope_type) where revoked_at is null;
create table public.editorial_documents (feature_id uuid primary key references public.features(id), schema_version integer not null default 1, working_document jsonb not null, revision_token uuid not null default gen_random_uuid(), author_id uuid not null references public.profiles(id), lifecycle_status text not null default 'draft' check(lifecycle_status in ('draft','submitted','changes_requested','approved','scheduled','published','archived')), updated_at timestamptz not null default now());
create table public.editorial_document_snapshots (id uuid primary key default gen_random_uuid(), feature_id uuid not null references public.features(id), schema_version integer not null, document jsonb not null, reason text not null, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.editorial_media_assets (id uuid primary key default gen_random_uuid(), feature_id uuid references public.features(id), uploader_id uuid not null references public.profiles(id), provider text not null default 'supabase-storage', storage_key text not null unique, mime_type text not null check(mime_type in ('image/jpeg','image/png','image/webp')), bytes bigint not null check(bytes>=0), width integer, height integer, alt_text text not null default '', caption text not null default '', source text not null default '', rights text not null default '', status text not null default 'processing_required' check(status in ('staged','processing_required','ready','published','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.editorial_access_grants enable row level security; alter table public.editorial_documents enable row level security; alter table public.editorial_document_snapshots enable row level security; alter table public.editorial_media_assets enable row level security;
create policy editorial_grants_admin_read on public.editorial_access_grants for select to authenticated using(public.open_panel_role()='admin' or user_id=auth.uid());
create policy editorial_documents_author_read on public.editorial_documents for select to authenticated using(author_id=auth.uid() or public.open_panel_role()='admin');
-- Mutations must be made through server-side RPC/API after grant and optimistic-token checks.
revoke all on public.editorial_access_grants,public.editorial_documents,public.editorial_document_snapshots,public.editorial_media_assets from anon,authenticated;
grant select on public.editorial_access_grants,public.editorial_documents to authenticated;
